[project]
name = "analyser-les-donnees-de-systemes-educatifs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.8,<3.10",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
    "ydata-profiling>=4.18.0",
]
